export const navLinks = [
    {
        id: "home",
        title: "Home",
        link: "/",
    },
    {
        id: "products",
        title: "Products",
        link: "/products",
    },
    {
        id: "cart",
        title: "Cart",
        link: "/cart",
    },
];

export const products = [
    {
        id: 1,
        name: "Apple",
        price: 100,
        discount: 20,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 2,
        name: "Banana",
        price: 200,
        discount: 10,
        rating: 4,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 3,
        name: "Orange",
        price: 300,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 4,
        name: "Mango",
        price: 400,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 5,
        name: "Grapes",
        price: 500,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 6,
        name: "Watermelon",
        price: 600,
        discount: 15,
        rating: 3,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 7,
        name: "Pineapple",
        price: 700,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
    {
        id: 8,
        name: "Strawberry",
        price: 800,
        rating: 5,
        amount: 1,
        company: "Apple",
        description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolores sit ut dolorum. Labore, consequatur qui rem nostrum ratione, accusamus suscipit recusandae voluptatem est voluptate cupiditate atque voluptatum. Delectus, eius voluptas.",
        image: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
        addedToCart: false,
        wishlisted: false,
    },
];
